# Generated by Django 4.2.15 on 2025-08-01 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qabriston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('karta_number', models.CharField(blank=True, max_length=20)),
                ('qator', models.CharField(blank=True, max_length=20)),
                ('qabr_soni', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('ism_familiyasi_marhum', models.CharField(blank=True, max_length=20)),
                ('yoshi', models.CharField(blank=True, max_length=20)),
                ('karta_number', models.CharField(blank=True, max_length=20)),
                ('qabr_soni', models.CharField(blank=True, max_length=20)),
                ('royhatga_olingan_joy', models.CharField(blank=True, max_length=20)),
                ('malumotnoma_num', models.CharField(blank=True, max_length=20)),
                ('uy_manzili', models.CharField(blank=True, max_length=20)),
                ('olim_sababi', models.CharField(blank=True, max_length=20)),
                ('qarindoshligi', models.CharField(blank=True, max_length=50)),
                ('ism_familiyasi_ishonchlivakil', models.CharField(blank=True, max_length=20)),
                ('telefon_numeri', models.CharField(blank=True, max_length=20)),
                ('gorkov_bilanmi', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/hujjat/')),
                ('malumotnoma_nomeri', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
