# Generated by Django 5.1.4 on 2025-01-08 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('passportdata', models.CharField(blank=True, max_length=20)),
                ('birthday', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
