# Generated by Django 5.1.4 on 2025-01-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodata',
            old_name='birthday',
            new_name='dalolatnoma_raqami',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='first_name',
            new_name='dalolatnoma_sanasi',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='last_name',
            new_name='malumot_berilgan_sana',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='passportdata',
            new_name='malumotnoma_num',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='data',
        ),
        migrations.AddField(
            model_name='infodata',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='infodata',
            name='olim_sababi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='qayt_qilingan_FHDY_bolim',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='tibbiyot_muassasasi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='tugilgan_vaqti',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='vafot_etgan_joy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='vafot_etgan_sana',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='vafot_etgan_shaxsning_JSHIR',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='yosh',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
