# Generated by Django 5.1.4 on 2025-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0002_rename_birthday_infodata_dalolatnoma_raqami_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qabriston',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(blank=True, max_length=20)),
                ('karta_number', models.CharField(blank=True, max_length=20)),
                ('qator', models.CharField(blank=True, max_length=20)),
                ('qabr_soni', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='infodata',
            name='karta_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='qabr_soni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='qator',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='royhatga_olingan_vaqt',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
