# Generated by Django 4.2.15 on 2025-04-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0003_qabriston_infodata_karta_number_infodata_qabr_soni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodata',
            old_name='dalolatnoma_raqami',
            new_name='JSHSHIR_ishonch_vakil',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='dalolatnoma_sanasi',
            new_name='JSHSHIR_olgan',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='karta_number',
            new_name='gorkov_bilanmi',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='malumot_berilgan_sana',
            new_name='ism_familiyasi',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='olim_sababi',
            new_name='ism_familiyasi_ishonchlivakil',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='qabr_soni',
            new_name='ism_familiyasi_marhum',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='qator',
            new_name='mahalla',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='qayt_qilingan_FHDY_bolim',
            new_name='marhumning_qarindoshligi',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='tugilgan_vaqti',
            new_name='qabriston_joy',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='full_name',
            new_name='qarindoshligi',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='vafot_etgan_joy',
            new_name='telefon_numeri',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='vafot_etgan_sana',
            new_name='tuman',
        ),
        migrations.RenameField(
            model_name='infodata',
            old_name='vafot_etgan_shaxsning_JSHIR',
            new_name='viloyat',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='yosh',
        ),
    ]
