# Generated by Django 4.2.15 on 2025-04-04 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('one_to_one', '0004_rename_dalolatnoma_raqami_infodata_jshshir_ishonch_vakil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infodata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
