# Generated by Django 4.2.15 on 2025-04-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0006_qabriston_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infodata',
            name='JSHSHIR_olgan',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='gorkov_bilanmi',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='ism_familiyasi',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='mahalla',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='marhumning_qarindoshligi',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='qabriston_joy',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='royhatga_olingan_vaqt',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='tibbiyot_muassasasi',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='tuman',
        ),
        migrations.RemoveField(
            model_name='infodata',
            name='viloyat',
        ),
    ]
