# Generated by Django 4.2.15 on 2025-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0007_remove_infodata_jshshir_olgan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hujjat/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
