# Generated by Django 4.2.15 on 2025-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0009_image_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infodata',
            old_name='JSHSHIR_ishonch_vakil',
            new_name='gorkov_bilanmi',
        ),
        migrations.AddField(
            model_name='infodata',
            name='karta_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='olim_sababi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='qabr_soni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='royhatga_olingan_joy',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='uy_manzili',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='infodata',
            name='yoshi',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
