# Generated by Django 4.2.15 on 2025-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0010_rename_jshshir_ishonch_vakil_infodata_gorkov_bilanmi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='malumotnoma_nomeri',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/hujjat/'),
        ),
    ]
