# Generated by Django 4.2.15 on 2025-07-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0011_rename_description_image_malumotnoma_nomeri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qabristonmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiyasi_marhum', models.CharField(blank=True, max_length=20)),
                ('years_old', models.CharField(blank=True, max_length=20)),
                ('years', models.CharField(blank=True, max_length=20)),
                ('karta_number', models.CharField(blank=True, max_length=20)),
                ('qator', models.CharField(blank=True, max_length=20)),
                ('qabr_soni', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('green', 'Yashil'), ('yellow', 'Sariq'), ('red', 'Qizil')], default='green', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Qabristonmap_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/cam/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='one_to_one.qabristonmap')),
            ],
        ),
    ]
