# Generated by Django 4.2.15 on 2025-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0012_qabristonmap_qabristonmap_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabristonmap',
            name='years_new',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
