# Generated by Django 4.2.15 on 2025-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0013_qabristonmap_years_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='GravePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karta_number', models.CharField(max_length=20)),
                ('qator', models.CharField(max_length=20)),
                ('after_qabr_soni', models.CharField(max_length=20)),
            ],
        ),
    ]
