# Generated by Django 4.2.15 on 2025-07-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0014_gravepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GravePath',
        ),
    ]
