# Generated by Django 4.2.15 on 2025-07-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_one', '0015_delete_gravepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qabristonmap',
            name='karta_number',
        ),
    ]
