# Generated by Django 4.2.15 on 2025-08-01 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cemeterys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('total_graves', models.PositiveIntegerField()),
                ('established', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graves', to='maskan.cemeterys')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=50000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskan.category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maskan.location')),
            ],
        ),
        migrations.CreateModel(
            name='Qabristonmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiyasi_marhum', models.CharField(blank=True, max_length=20)),
                ('years_old', models.CharField(blank=True, max_length=20)),
                ('years', models.CharField(blank=True, max_length=20)),
                ('years_new', models.CharField(blank=True, max_length=20)),
                ('qator', models.CharField(blank=True, max_length=20)),
                ('qabr_soni', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('green', 'Yashil'), ('yellow', 'Sariq'), ('red', 'Qizil')], default='green', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabristonmaps', to='maskan.product')),
            ],
        ),
        migrations.CreateModel(
            name='Qabristonmap_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/cam/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maskan.qabristonmap')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=100)),
                ('job', models.CharField(default='Unemployed', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('old_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maskan.product')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('grave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='maskan.grave')),
            ],
        ),
    ]
