# Generated by Django 4.2.15 on 2025-08-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grave',
            name='cemetery',
        ),
        migrations.RemoveField(
            model_name='person',
            name='grave',
        ),
        migrations.DeleteModel(
            name='Cemeterys',
        ),
        migrations.DeleteModel(
            name='Grave',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
