# Generated by Django 4.2.15 on 2025-07-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemeterys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('total_graves', models.PositiveIntegerField()),
                ('established', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('cemetery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graves', to='maskan.cemeterys')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('grave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='maskan.grave')),
            ],
        ),
    ]
