# Generated by Django 4.2.15 on 2025-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
