# Generated by Django 4.2.15 on 2025-08-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0002_remove_grave_cemetery_remove_person_grave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tuman/Shahar', 'verbose_name_plural': 'Tuman/Shaharlar'},
        ),
    ]
