# Generated by Django 4.2.15 on 2025-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0002_profile_extra_phone_number_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
