# Generated by Django 4.2.15 on 2025-08-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tuman Shahar', 'verbose_name_plural': 'Tumanlar Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='qabristonmap',
            options={'verbose_name': 'Qabriston', 'verbose_name_plural': 'Qabristonlar'},
        ),
    ]
