# Generated by Django 4.2.15 on 2025-08-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0003_remove_profile_extra_phone_number_profile_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabristonmap',
            name='years',
            field=models.CharField(blank=True, max_length=20, verbose_name='Yil oraliği'),
        ),
    ]
