# Generated by Django 4.2.15 on 2025-08-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0004_alter_category_options_alter_qabristonmap_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qabristonmap',
            options={'verbose_name': 'Marhum', 'verbose_name_plural': 'Marhumlar'},
        ),
        migrations.AlterField(
            model_name='qabristonmap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabristonmaps', to='maskan.product', verbose_name='Qabriston'),
        ),
    ]
