# Generated by Django 4.2.15 on 2025-08-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0004_alter_qabristonmap_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maskan.product', verbose_name='Ruxsat berilgan qabriston'),
        ),
    ]
