# Generated by Django 4.2.15 on 2025-07-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0005_location_remove_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='location',
        ),
    ]
