# Generated by Django 4.2.15 on 2025-08-02 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0005_alter_qabristonmap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabristonmap',
            name='years_new',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Faqat 4 xonali yil kiriting, masalan: 1990 yoki 2023', regex='^\\d{4}$')], verbose_name='Vafot yili'),
        ),
        migrations.AlterField(
            model_name='qabristonmap',
            name='years_old',
            field=models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Faqat 4 xonali yil kiriting, masalan: 1990 yoki 2023', regex='^\\d{4}$')], verbose_name='Tug‘ilgan yil'),
        ),
    ]
