# Generated by Django 4.2.15 on 2025-08-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0006_alter_qabristonmap_years_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabristonmap',
            name='yosh',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Yosh'),
        ),
    ]
