# Generated by Django 4.2.15 on 2025-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0006_rename_price_product_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
