# Generated by Django 4.2.15 on 2025-08-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0007_qabristonmap_yosh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qabristonmap_image',
            options={'verbose_name': 'qabrnig rasmi', 'verbose_name_plural': 'Qabrning rasmlari'},
        ),
    ]
