# Generated by Django 4.2.15 on 2025-08-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0008_alter_qabristonmap_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tuman/Shahar', 'verbose_name_plural': 'Tuman/Shaharlar'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokatsiya', 'verbose_name_plural': 'Lokatsiyalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Qabriston', 'verbose_name_plural': 'Qabristonlar'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maskan.category', verbose_name='Tuman/Shahar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maskan.location', verbose_name='Lokatsiya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Qabriston nomi'),
        ),
    ]
