# Generated by Django 4.2.15 on 2025-08-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0010_alter_productimage_options_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Tuman Shahar', 'verbose_name_plural': 'Tumanlar Shaharlar'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
